-- MySQL Script generated by MySQL Workbench
-- Tue Jul  3 12:31:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `uid` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `unickname` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `userstate` TINYINT(1) NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupchat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groupchat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groupchat` (
  `gid` INT NOT NULL AUTO_INCREMENT,
  `announcement` VARCHAR(200) NULL,
  `groupname` VARCHAR(45) NOT NULL,
  `user_uid` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`gid`),
  INDEX `fk_group_user_idx` (`user_uid` ASC),
  CONSTRAINT `fk_group_user`
    FOREIGN KEY (`user_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friendship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`friendship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`friendship` (
  `user_uid1` VARCHAR(20) NOT NULL,
  `user_uid2` VARCHAR(20) NOT NULL,
  INDEX `fk_friendship_user1_idx` (`user_uid1` ASC),
  INDEX `fk_friendship_user2_idx` (`user_uid2` ASC),
  PRIMARY KEY (`user_uid1`, `user_uid2`),
  CONSTRAINT `fk_friendship_user1`
    FOREIGN KEY (`user_uid1`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendship_user2`
    FOREIGN KEY (`user_uid2`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupmember`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groupmember` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groupmember` (
  `group_gid` INT NOT NULL,
  `user_uid` VARCHAR(20) NOT NULL,
  INDEX `fk_groupmember_group1_idx` (`group_gid` ASC),
  INDEX `fk_groupmember_user1_idx` (`user_uid` ASC),
  PRIMARY KEY (`group_gid`, `user_uid`),
  CONSTRAINT `fk_groupmember_group1`
    FOREIGN KEY (`group_gid`)
    REFERENCES `mydb`.`groupchat` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupmember_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friendadd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`friendadd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`friendadd` (
  `state` TINYINT(1) NOT NULL,
  `sender_uid` VARCHAR(20) NOT NULL,
  `receiver_uid` VARCHAR(20) NOT NULL,
  INDEX `fk_friendadd_user1_idx` (`sender_uid` ASC),
  INDEX `fk_friendadd_user2_idx` (`receiver_uid` ASC),
  PRIMARY KEY (`receiver_uid`, `sender_uid`),
  CONSTRAINT `fk_friendadd_user1`
    FOREIGN KEY (`sender_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendadd_user2`
    FOREIGN KEY (`receiver_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupinvite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groupinvite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groupinvite` (
  `group_gid` INT NOT NULL,
  `user_uid` VARCHAR(20) NOT NULL,
  INDEX `fk_groupinvite_group1_idx` (`group_gid` ASC),
  INDEX `fk_groupinvite_user1_idx` (`user_uid` ASC),
  PRIMARY KEY (`group_gid`, `user_uid`),
  CONSTRAINT `fk_groupinvite_group1`
    FOREIGN KEY (`group_gid`)
    REFERENCES `mydb`.`groupchat` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupinvite_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupapply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groupapply` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groupapply` (
  `user_uid` VARCHAR(20) NOT NULL,
  `group_gid` INT NOT NULL,
  INDEX `fk_groupapply_user1_idx` (`user_uid` ASC),
  INDEX `fk_groupapply_group1_idx` (`group_gid` ASC),
  PRIMARY KEY (`user_uid`, `group_gid`),
  CONSTRAINT `fk_groupapply_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupapply_group1`
    FOREIGN KEY (`group_gid`)
    REFERENCES `mydb`.`groupchat` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friendrecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`friendrecord` ;

CREATE TABLE IF NOT EXISTS `mydb`.`friendrecord` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NULL,
  `sender_uid` VARCHAR(20) NOT NULL,
  `receiver_uid` VARCHAR(20) NOT NULL,
  `recordtime` DATETIME(3) NULL,
  `isread` TINYINT(1) NOT NULL,
  PRIMARY KEY (`rid`),
  INDEX `fk_friendrecord_user1_idx` (`sender_uid` ASC),
  INDEX `fk_friendrecord_user2_idx` (`receiver_uid` ASC),
  CONSTRAINT `fk_friendrecord_user1`
    FOREIGN KEY (`sender_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendrecord_user2`
    FOREIGN KEY (`receiver_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grouprecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grouprecord` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grouprecord` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NULL,
  `user_uid` VARCHAR(20) NOT NULL,
  `group_gid` INT NOT NULL,
  `recordtime` DATETIME(3) NULL,
  PRIMARY KEY (`rid`),
  INDEX `fk_grouprecord_user1_idx` (`user_uid` ASC),
  INDEX `fk_grouprecord_group1_idx` (`group_gid` ASC),
  CONSTRAINT `fk_grouprecord_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grouprecord_group1`
    FOREIGN KEY (`group_gid`)
    REFERENCES `mydb`.`groupchat` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file` (
  `fid` INT NOT NULL AUTO_INCREMENT,
  `content` LONGBLOB NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`fid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupnotread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groupnotread` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groupnotread` (
  `rid` INT NOT NULL,
  `receiver_id` VARCHAR(20) NOT NULL,
  `gid` INT NULL,
  PRIMARY KEY (`rid`, `receiver_id`),
  INDEX `uid_idx` (`receiver_id` ASC),
  INDEX `gid_idx` (`gid` ASC),
  CONSTRAINT `rid`
    FOREIGN KEY (`rid`)
    REFERENCES `mydb`.`grouprecord` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uid`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gid`
    FOREIGN KEY (`gid`)
    REFERENCES `mydb`.`grouprecord` (`group_gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
